### ISSUE TITLE
Not reacting to my contract

### ISSUE THREAD

**Issue by beamercola** [jpgboi/loot-nft-sales-bot#2]
this is freaking awesome - i'm trying to hook this up to our discord for this contract (https://etherscan.io/address/0x3c48D717c981b460736ba1eBcBC2c0CC54601ab4) - railway says Listening For Sales but  as sales come in I don't get the messages in discord or errors in the log

**Comment by jpgboi** [comment]
Bot only listens for `Transfer` events that have some value attached to it. It only sends messages where the ETH or WETH transferred is greater than 0.

**Comment by jpgboi** [comment]
You could fork it and remove the if statement to send messages for all transfers.
https://github.com/jpgboi/loot-nft-sales-bot/blob/3b061c5ff1e0681dbf70a50892b6ae48f3c69796/src/index.ts#L35
